---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rwolf

The rwolf package installs Romano-Wolf multiple-hypothesis-adjusted p-values for objects
of type `fixest_multi` from the `fixest` package.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("s3alfisc/rwolf")
```
## Example

```{r}
library(fixest)
library(rwolf)

set.seed(123)
N <- 1000
X1 <- rnorm(N)
Y1 <- 1 + 0.2 * X1 + rnorm(N)
Y2 <- 1 + 0.1 * X1 + rnorm(N)
cluster <- rep(1:50, 1000 / 50)

data <- data.frame(Y1 = Y1, 
                   Y2 = Y2, 
                   X1 = X1, 
                   cluster = cluster)

res <- feols(c(Y1, Y2) ~ X1, data = data, cluster = ~ cluster)
class(res)
summary(res)

rwolf_res <- rwolf(models = res, parameter = "X1", B = 100)
summary.rwolf(rwolf_res)
```

